-- Sync all tables to match schema.prisma and eliminate any Prisma P2022 ColumnNotFound errors

-- 1. Papers Table
ALTER TABLE "papers"
ADD COLUMN IF NOT EXISTS "is_official_code" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "hf_upvotes" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "trending_score" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "discovery_source" TEXT,
ADD COLUMN IF NOT EXISTS "authors" TEXT,
ADD COLUMN IF NOT EXISTS "domain" TEXT,
ADD COLUMN IF NOT EXISTS "task" TEXT,
ADD COLUMN IF NOT EXISTS "huggingface_url" TEXT,
ADD COLUMN IF NOT EXISTS "hf_model_url" TEXT,
ADD COLUMN IF NOT EXISTS "hf_url" TEXT,
ADD COLUMN IF NOT EXISTS "importance_score" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "venue" TEXT,
ADD COLUMN IF NOT EXISTS "organization" TEXT,
ADD COLUMN IF NOT EXISTS "github_hourly_increase" DOUBLE PRECISION DEFAULT 1.0;

-- 2. Benchmarks Table
ALTER TABLE "benchmarks"
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "domain" TEXT,
ADD COLUMN IF NOT EXISTS "task" TEXT,
ADD COLUMN IF NOT EXISTS "metric" TEXT,
ADD COLUMN IF NOT EXISTS "year" INTEGER,
ADD COLUMN IF NOT EXISTS "papers_evaluated" INTEGER,
ADD COLUMN IF NOT EXISTS "is_popular" BOOLEAN,
ADD COLUMN IF NOT EXISTS "is_trending" BOOLEAN,
ADD COLUMN IF NOT EXISTS "is_recently_added" BOOLEAN,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "category" TEXT,
ADD COLUMN IF NOT EXISTS "status" TEXT,
ADD COLUMN IF NOT EXISTS "results_count" INTEGER,
ADD COLUMN IF NOT EXISTS "models_count" INTEGER,
ADD COLUMN IF NOT EXISTS "paper_title" TEXT,
ADD COLUMN IF NOT EXISTS "paper_url" TEXT,
ADD COLUMN IF NOT EXISTS "repo_url" TEXT,
ADD COLUMN IF NOT EXISTS "dataset_url" TEXT,
ADD COLUMN IF NOT EXISTS "top_models" TEXT[],
ADD COLUMN IF NOT EXISTS "modality" TEXT,
ADD COLUMN IF NOT EXISTS "benchmark_url" TEXT;

-- 3. Rankings Table
ALTER TABLE "rankings"
ADD COLUMN IF NOT EXISTS "score" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "score_str" TEXT,
ADD COLUMN IF NOT EXISTS "model_name" TEXT,
ADD COLUMN IF NOT EXISTS "metric" TEXT,
ADD COLUMN IF NOT EXISTS "url" TEXT,
ADD COLUMN IF NOT EXISTS "source" TEXT,
ADD COLUMN IF NOT EXISTS "model_id" TEXT,
ADD COLUMN IF NOT EXISTS "organization" TEXT,
ADD COLUMN IF NOT EXISTS "verified" BOOLEAN,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "resultDate" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "previousRank" INTEGER,
ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT DEFAULT 'https://paperswithcode.com/sota',
ADD COLUMN IF NOT EXISTS "result_date" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "source_url" TEXT;

-- 4. Tasks Table
ALTER TABLE "tasks"
ADD COLUMN IF NOT EXISTS "domain" TEXT,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(6);

-- 5. Methods Table
ALTER TABLE "methods"
ADD COLUMN IF NOT EXISTS "category" TEXT,
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(6),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(6);
